-- Boreas Power Personnel Planner import (migration from spreadsheet)
-- Run in Supabase SQL editor

DO $$
DECLARE
  co_id uuid;
  emp_id uuid;
BEGIN
  SELECT id INTO co_id FROM public.companies WHERE slug = 'boreaspower';
  IF co_id IS NULL THEN RAISE EXCEPTION 'boreaspower company not found'; END IF;

  -- Get Fraser McKenzie person_id (Employee row maps to this person)
  SELECT id INTO emp_id FROM public.people
    WHERE company_id = co_id AND name ILIKE '%Fraser%McKenzie%'
    LIMIT 1;

  -- Insert assignments
  INSERT INTO public.planner_assignments
    (company_id, person_id, person_label, date, type, client, scope, location)
  VALUES
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-01-01', 'Public Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-01-02', 'Public Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-01-06', 'Meeting', 'OCU Nettworx', NULL, 'Huntly Depot'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-01-07', 'Personal Appointment', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-01-09', 'Meeting', 'Other', 'Acutest Sales', 'Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-02-06', 'Meeting', 'Spirit of the Spindrift', 'Safety Rules', 'Online (Teams)'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-03-02', 'Meeting', 'Stern Energy', 'Startup Call', 'Online (Teams)'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-03-25', 'Personal Appointment', NULL, 'Van Service', 'Land Rover, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-03-30', 'Training', NULL, 'Enhanced First Aid', 'Aurora Training, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-03-31', 'Training', NULL, 'Enhanced First Aid', 'Aurora Training, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-01', 'Training', NULL, 'Enhanced First Aid', 'Aurora Training, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-20', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-21', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-22', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-23', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-24', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-27', 'Meeting', 'Spirit of the Spindrift', 'OSR Review @ 11:00', 'Teams Meeting'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-04-30', 'Other', 'Other', 'Buar Event @ 09:30', 'Vp ESS, Glasgow'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-05-08', 'Personal Appointment', NULL, 'Dentist @ 16:00', 'Bupa, Dignwall'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-05-13', 'Other', NULL, 'Van in Garage', 'Land Rover, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-05-14', 'Other', NULL, 'All-Energy', 'SEC, Glasgow'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-03', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-04', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-05', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-06', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-07', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-08', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-09', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-23', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-06-24', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-01', 'Training', NULL, 'Skanwear Webinar', 'Zoom Event @ 15:00'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-02', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-03', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-04', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-05', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-14', 'Meeting', 'OCU', 'Shetland SAP Requirements', 'Teams @ 12:00'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-07-27', 'Personal Appointment', NULL, 'Van Tyres', 'ITS, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-08-03', 'Training', NULL, 'CCNGS Safety Passport', '3T Global, Aberdeen'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-08-04', 'Training', NULL, 'CCNGS Safety Passport', '3T Global, Aberdeen'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-08-24', 'Personal Appointment', NULL, 'Van in garage', 'Land Rover, Inverness'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-02', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-07', 'Personal Appointment', NULL, 'Fiesta MOT', 'Culloden Garage @ 08:00'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-12', 'Travel', 'OCU', 'Inverness - Shetland', 'Flight @ 09:25'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-14', 'Travel', 'OCU', 'Shetland - Inverness', 'Flight @ 11:50'),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-15', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-16', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-22', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-10-23', 'Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-12-25', 'Public Holiday', NULL, NULL, NULL),
  (co_id, NULL, 'Fraser McKenzie (Director)', '2026-12-28', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-01', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-01', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-02', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-02', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-11', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-12', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-13', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-14', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-15', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-16', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-17', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-18', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-19', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-20', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-21', 'Work', 'European Energy', 'SAP / Test Engineer', 'Beatrice Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-23', 'Work', 'OTP Engineering', 'Cable Test Engineer', 'Monan Wind Farm, Western Isles'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-01-24', 'Work', 'OTP Engineering', 'Cable Test Engineer', 'Monan Wind Farm, Western Isles'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-03', 'Work', 'OTP Engineering', 'Commissioning Technician', 'Monan Wind Farm, Western Isles'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-04', 'Work', 'OTP Engineering', 'Commissioning Technician', 'Monan Wind Farm, Western Isles'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-09', 'Work', 'Advance Grid Solutions', 'Operational Readiness Audit', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-10', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-11', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-12', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-13', 'Work', 'European Energy', 'SAP - Access to Customer Sub', 'Kincraig Solar Farm, Aberdeenshire'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-17', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-18', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-19', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-20', 'Work', 'Advance Grid Solutions', 'SAP - Energisation Planning', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-23', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-24', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-25', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-25', 'Training', 'Monster Power', 'H&MV Engineering - SAP Panel', 'Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-26', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-02-27', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-02', 'Meeting', 'Ventus Energy', 'Work Planning', 'Online (Teams)'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-02', 'Meeting', 'SJ Power Solutions', 'Work Planning', 'Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-03', 'Travel', 'Monster Power', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-04', 'Training', 'Monster Power', 'Vestas ESQ', 'Hamburg, Germany'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-05', 'Training', 'Monster Power', 'Vestas ESQ', 'Hamburg, Germany'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-06', 'Training', 'Monster Power', 'Vestas LOTO Level 2', 'Hamburg, Germany'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-11', 'Work', 'SJ Power Solutions', 'Commissioning / Test Engineer', 'Standingfauld Solar Farm, Muthill'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-12', 'Work', 'SJ Power Solutions', 'Commissioning / Test Engineer', 'Standingfauld Solar Farm, Muthill'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-13', 'Work', 'SJ Power Solutions', 'Commissioning / Test Engineer', 'Standingfauld Solar Farm, Muthill'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-16', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-17', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-18', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-19', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-20', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-21', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-22', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Moray East Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-23', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-24', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-25', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-26', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-03-27', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-02', 'Work', 'Monster Power', 'Commissioning Engineer', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-07', 'Work', 'Advance Grid Solutions', 'Consultant - Incident Investigation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-08', 'Work', 'Advance Grid Solutions', 'Consultant - Incident Investigation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-09', 'Work', 'Advance Grid Solutions', 'Consultant - Incident Investigation', 'Erskine BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-13', 'Work', 'European Energy', 'SAP - LV Energisation', 'Kincraig Solar Farm, Aberdeenshire'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-14', 'Work', 'European Energy', 'SAP - LV Energisation', 'Kincraig Solar Farm, Aberdeenshire'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-15', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-15', 'Work', 'European Energy', 'SAP - LV Energisation', 'Kincraig Solar Farm, Aberdeenshire'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-16', 'Work', 'Ventus Energy', 'SAP - OSP Inspections', 'Seagreen Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-17', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-20', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-20', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-21', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-21', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-22', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-22', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-24', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-24', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-27', 'Work', 'Monster Power', 'Site Visit - H&MV Engineering', 'Neilston BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-28', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Thornton BESS, York'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-29', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Thornton BESS, York'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-04-30', 'Work', 'Advance Grid Solutions', 'Cable Test Engineer', 'Drumcross BESS, Livingstone'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-01', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Neilston BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-05', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Neilston BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-06', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Neilston BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-07', 'Work', 'Advance Grid Solutions', 'Site Visit', 'Dalmarnock BESS and Drumcross BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-08', 'Other', 'Other', 'Offshore Medical Assessment', 'Thistle Occupational Health, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-11', 'Training', NULL, 'GWO BST Refresher', 'Aurora Training, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-12', 'Training', NULL, 'GWO BST Refresher', 'Aurora Training, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-13', 'Training', NULL, 'GWO BST Refresher', 'Aurora Training, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-14', 'Training', NULL, 'Skanwear Webinar', 'Zoom Event @ 14:00'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-15', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-18', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-19', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-20', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-21', 'Work', 'IES UK', 'Cable Test Engineer', 'Lochay Power Station, Killin'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-22', 'Work', 'IES UK', 'Cable Test Engineer', 'Lochay Power Station, Killin'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-26', 'Work', 'Monster Power', 'Commissioning Technician', 'Dyce, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-27', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-28', 'Work', 'Advance Grid Solutions', 'SAP - 33kV System Energisation', 'Drumcross BESS, Livingston'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-29', 'Work', 'Monster Power', 'Commissioning Technician', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-05-31', 'Travel', 'Monster Power', NULL, 'Cairnryan W/F,  Stranraer'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-01', 'Work', 'Monster Power', 'Commissioning Technician', 'Cairnryan W/F,  Stranraer'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-02', 'Work', 'Monster Power', 'Commissioning Technician', 'Cairnryan W/F,  Stranraer'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-03', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-03', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-04', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-04', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-05', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-05', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-06', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-06', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-07', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-07', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-08', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-08', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-09', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-09', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-15', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-16', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-17', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-18', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Coalburn BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-19', 'Work', 'Monster Power', '33kV SAP - H&MV Engineering', 'Coalburn  BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-22', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-24', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-24', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-25', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-26', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-29', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-06-30', 'Work', 'Advance Grid Solutions', 'Site Visit', 'Dalmarnock BESS, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-01', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-02', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-02', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-03', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-03', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-04', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-04', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-05', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-05', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-06', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-07', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-08', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-09', 'Work', 'Monster Power', '33kV SAP', 'Arderseir Port, Inverenss'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-10', 'Work', 'Monster Power', '33kV SAP', 'Arderseir Port, Inverenss'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-13', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-14', 'Work', 'IES UK', 'Cable Test Engineer', 'Dochfour Estate'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-15', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-16', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-17', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-18', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-19', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-20', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-21', 'Work', 'Ventus Energy', '132kV SAP', 'Dudgeon Export Cable Route, Norwich'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-22', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-22', 'Work', 'Ventus Energy', '33kV SAP', 'Auchrobert W/F, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-24', 'Work', 'IES UK', 'Cable Test Engineer', 'Bakkafrost, Kishorn'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-24', 'Work', 'OTP Engineering', 'Cable Test Engineer', 'Somerby WTG, Dingwall'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-28', 'Work', 'OCU', '33kV SAP', 'Rothienorman BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-29', 'Work', 'OTP Engineering', 'Fault Response', 'Somerby WTG, Dingwall'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-07-31', 'Work', 'OTP Engineering', 'Fault Response', 'Somerby WTG, Dingwall'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-01', 'Work', 'IES UK', 'Cable Test Engineer', 'Bakkafrost, Kishorn'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-05', 'Work', 'Monster Power', 'Commissioning Technician', 'Arderseir Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-06', 'Work', 'Monster Power', 'Commissioning Technician', 'Arderseir Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-07', 'Work', 'Monster Power', 'Commissioning Technician', 'Arderseir Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-09', 'Travel', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-10', 'Work', 'SFTS', 'Cable Test Engineer', 'South Clyde Energy Centre, Glasgow'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-12', 'Work', 'SFTS', 'Cable Test Engineer', 'NNG Onshore Substation, Dunbar'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-13', 'Work', 'OTP Engineering', 'Fault Response', 'Somerby WTG, Dingwall'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-16', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-17', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Seagreen Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-18', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Seagreen Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-19', 'Work', 'Ventus Energy', 'SAP / Test Engineer', 'Seagreen Offshore Wind Farm'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-20', 'Travel', 'Ventus Energy', NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-25', 'Training', 'Ventus Energy', 'SSER SAP Assessment', 'Blackhillock'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-26', 'Training', 'Ventus Energy', 'SSER SAP Assessment', 'Blackhillock'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-27', 'Training', 'Ventus Energy', 'SSER SAP Assessment', 'Blackhillock'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-28', 'Work', 'Monster Power', 'Commissioning Technician', 'Ardersier Port, Inverness'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-08-31', 'Work', 'SFTS', 'Cable Test Engineer', 'Corriemoillie W/F'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-01', 'Travel', 'SFTS', 'Collect Test Equipment', 'Vp ESS, Kintore'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-02', 'Work', 'SFTS', 'Cable Test Engineer', 'Corriemoillie W/F'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-03', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-07', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-08', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-09', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-10', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-11', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-14', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-15', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-16', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-17', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-18', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-21', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-22', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-23', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-24', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-25', 'Work', 'OCU', '33kV SAP', 'Dyce BESS, Aberdeen'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-09-30', 'Work', 'Advance Grid Solutions', 'Site Visit', 'Bankside BESS, Falkirk'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-02', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-02', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-05', 'Work', 'Ventus Energy', 'Unconfirmed', 'Beatrice W/F'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-06', 'Work', 'Ventus Energy', 'Unconfirmed', 'Beatrice W/F'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-08', 'Work', 'SJ Power Solutions', 'Unconfirmed', 'Invergordon'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-12', 'Work', 'OCU', 'Site Visit', 'Shetland BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-13', 'Work', 'OCU', 'Site Visit', 'Shetland BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-14', 'Work', 'OCU', 'Site Visit', 'Shetland BESS'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-15', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-15', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-16', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-16', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-19', 'Training', NULL, 'SSEN SAP Assessment', 'Perth Training School'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-20', 'Training', NULL, 'SSEN SAP Assessment', 'Perth Training School'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-21', 'Training', NULL, 'SSEN SAP Assessment', 'Perth Training School'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-22', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-22', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-10-23', 'Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-11-18', 'Work', 'SFTS', 'Test Engineer', 'TBC'),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-12-25', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-12-25', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-12-28', 'Public Holiday', NULL, NULL, NULL),
  (co_id, emp_id, 'Fraser McKenzie (Employee)', '2026-12-28', 'Public Holiday', NULL, NULL, NULL)
  ON CONFLICT (person_id, date) WHERE person_id IS NOT NULL DO UPDATE SET
    type = EXCLUDED.type,
    client = EXCLUDED.client,
    scope = EXCLUDED.scope,
    location = EXCLUDED.location,
    updated_at = now();

  RAISE NOTICE 'Planner import complete: % rows upserted', 270;
END $$;